### PR TITLE
Rename gem from lotus to hanami

### PR DESCRIPTION
**Pull request by davydovanton**
Hello, lotus was renamed to hanami and I want to help for your gem too :star2:

### CODE REVIEW

**Comment by Nerian** [comment]
Cool, did you check that it still works?

**Comment by davydovanton** [comment]
Yes. I'll check this tomorrow on my application

**Comment by davydovanton** [comment]
so, I checked my changes and all worked fine.

**Comment by Nerian** [comment]
Awesome, good job. I will merge and publish.

**Comment by davydovanton** [comment]
thanks for merge :+1:

**Pull request merged**
